### ISSUE TITLE
¿Proyecto descontinuado?

### ISSUE THREAD

**Issue by cz9dev** [jdsdhp/enzona-payment-embedded#7]
Hola, seguirás el proyecto o lo has descontinuado, es que veo que hace 7 meces no subes cambios y quiero estar seguro antes de utilizarlo en mis proyectos. Saludos y felicitaciones por lo que estas haciendo. Muy bueno para el comercio en linea y el desarrollo de app en Cuba

**Comment by jdsdhp** [comment]
El proyecto se encuentra estable y en mantenimiento, no se ha descontinuado, no se han reportado bugs de lo que se tiene desarrollado hasta el momento. No se ha trabajado en alguna nueva funcionalidad por temas de tiempo pero aceptamos cualquier PR con mejoras o sugerencia. Saludos!
