### ISSUE TITLE
número de transacción

### ISSUE THREAD

**Issue by cz9dev** [jdsdhp/enzona-payment-embedded#9]
Hola necesito una ves realizado el pago correctamente obtener el numero de la transacción para insertarlo en mi DB como referencia al pago, algo así como:
```kt
val transactionSignature = response.transactionSignature
```
Pero no encuentro forma en tu librería, de echo el response de cuando creo el pago no tiene ese valor, mirando mi logcat me percate que al final del pago en los log veo algo como esto **,"transaction_signature":"YLaMoC3opHMh"}** pero no encuentro como obtenerlo. agradecería tu ayuda

**Comment by jdsdhp** [comment]
El identificador de la transacción esta determinado por `transaction_uuid`

**Comment by cz9dev** [comment]
> El identificador de la transacción esta determinado por `transaction_uuid`

Ok, lo veo pero es que ese identificador no lo veo en la interfaz de enzona, necesitaba algo como el #Op. ENZONA	que si sale en la web de enzona y se parece mas a lo que nos envía por sms cuando nos transfieren. ¿no se si me entiendes?, cuando alguien te transfiere no te llega el identificador de la transacción si no algo como ON0NccolAKXr que se parece mas a el campo que sale en la interfaz del ENZANA en la columna #Op. ENZONA

**Comment by jdsdhp** [comment]
Entiendo, quizás te refieres al `merchant_op_id` o al `invoice_number`. Ambos son identificadores que puedes usar internamente por el propio comercio, es decir, los generas y los envías al crear el pago. Son internos, Enzona te los va a devolver en cada petición a partir de la creación del pago y son útiles cuando quieres asociar alguna operación de tu negocio en una transacción de Enzona (`transaction_uuid`).

Revisa la app de ejemplo, ambos salen como inputs para que puedas crear el pago, solo necesitas generarlo a tu forma.

**Comment by cz9dev** [comment]
Si es el caso doy por cerrado este asunto, **gracias**
